name: phantom

# include:
#   - ../docker-compose.networks.yml
#   - ../docker-compose.volumes.yml

services:
  auto-m4b:
    # image: seanap/auto-m4b
    # build: https://github.com/brandonscript/auto-m4b.git
    # stdin_open: true # docker run -i
    # tty: true # docker run -t
    build:
      context: .
      target: debug
      args:
        PUID: 1000
        PGID: 1000
    container_name: auto-m4b
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./config:/config:rw
      # - /etc/docker/auto-m4b/auto-m4b-tool.sh:/auto-m4b-tool.sh:ro
      # - ragnarok-media:/media:rw
      - ./sheesh:/sandbox:rw
      # - downloads:/path/to/mount/downloads:rw
    environment:
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - MAX_CHAPTER_LENGTH=15,30
      # - INBOX_FOLDER=/media/Books/Audiobooks/#auto-m4b/inbox
      # - CONVERTED_FOLDER=/media/Books/Audiobooks/#auto-m4b/converted
      # - ARCHIVE_FOLDER=/media/Books/Audiobooks/#auto-m4b/archive
      # - BACKUP_FOLDER=/media/Books/Audiobooks/#auto-m4b/backup
      # - WORKING_FOLDER=/tmp/auto-m4b
      - ARCHIVE_FOLDER=/sandbox/archive
      - BACKUP_FOLDER=/sandbox/backup
      - CONVERTED_FOLDER=/sandbox/converted
      - INBOX_FOLDER=/sandbox/inbox
      - WORKING_FOLDER=/sandbox/working
      - OVERWRITE_EXISTING=Y
      - FLATTEN_MULTI_DISC_BOOKS=Y
      - CONVERT_SERIES=Y
      - BACKUP=Y
      - DEBUG=Y
      - PLEX_FORMAT=Y
      - TZ=America/Chicago
# volumes:
#   downloads:
#     driver_opts:
#       type: cifs
#       o: username={username},password={password},uid=1000,gid=1000,vers=3.0,rw
#       device: //{nas-ip-address}/{share-name}
